### ISSUE TITLE
DEEPLX_API_URL 的格式

### ISSUE THREAD

**Issue by spysir** [bestZwei/LibreTranslator#1]
请问大佬，假设自建的DEEPLX的TOKEN是123456
那么这样写的格式对吗
https://api.deeplx.org/123456

**Comment by bestZwei** [comment]
没用过自建。你试试，请求格式应该一样

**Comment by spysir** [comment]
> 没用过自建。你试试，请求格式应该一样

经过测试，连接自建的DEEPLX API
1.https://api.deeplx.org/123456
2.https://api.deeplx.org/translate?token=123456
都无法使用，但是像沉浸式翻译，简约翻译等浏览器插件使用第二种格式是可以正常使用的，DEEPLX的作者也规定了要用第二种格式

![deeplx](https://github.com/user-attachments/assets/8078bc9e-5b0e-497e-ac28-fcc234da1488)

**Comment by bestZwei** [comment]
![image](https://github.com/user-attachments/assets/92bee1f7-c7a5-493a-9c94-448332e2c67a)
现在只能 REACT_APP_DEEPLX_API_URL 设置成 https://api.deeplx.org ，REACT_APP_PASSWORD 设置成你的 TOKEN 123456，等会我再改一下代码

**Comment by bestZwei** [comment]
修了，看Readme文档

**Comment by spysir** [comment]
> 修了，看Readme文档

依然无法使用
变量设置如下
![deeplx](https://github.com/user-attachments/assets/06b68a35-16c5-4dd1-83c2-9528290500a8)

**Comment by bestZwei** [comment]
你同步更新了代码吗？现在 请求链接是 **REACT_APP_DEEPLX_API_URL**/translate?token=**REACT_APP_API_TOKEN** ，你按照你的URL和TOKEN填这两个环境变量

**Comment by spysir** [comment]
搞掂了，原来是API URL 后面多了个斜杠 /
