### ISSUE TITLE
显示翻译错误，难道是因为API_TOKEN随便填的缘故？应该填deeplx的api吗？

### ISSUE THREAD

**Issue by gitehabu** [bestZwei/LibreTranslator#3]
确定可以？按照github页面操作了，结果是翻译错误。

DEEPLX_API_URL:这个填写正确

PASSWORD（可选）: 这个也写了

NODE_OPTIONS:--openssl-legacy-provider这个照抄了

API_TOKEN：这个是真的随便填了

难道是因为API_TOKEN随便填的缘故？应该填deeplx的api吗？

**Comment by bestZwei** [comment]
刚刚在调试，修了，看Readme文档重新部署，还是失败告诉我

**Comment by gitehabu** [comment]
已解决，谢谢咯🙏
